# Generated by Django 5.2.7 on 2026-01-25 01:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtisteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_salon', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('date_expiration_abonnement', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('artiste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='artiste.artisteprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('COIFFURE_H', 'Coiffure Homme'), ('COIFFURE_F', 'Coiffure Femme'), ('MAKEUP', 'Make-up professionnel'), ('ONGLERIE', 'Onglerie')], max_length=20)),
                ('nom_prestation', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('duree_estimee', models.PositiveIntegerField(default=30)),
                ('artiste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='artiste.artisteprofile')),
            ],
        ),
        migrations.AddIndex(
            model_name='artisteprofile',
            index=models.Index(fields=['is_active'], name='artiste_art_is_acti_0d0d8c_idx'),
        ),
        migrations.AddIndex(
            model_name='artisteprofile',
            index=models.Index(fields=['date_expiration_abonnement'], name='artiste_art_date_ex_f27018_idx'),
        ),
    ]
